### ISSUE TITLE
ReferenceError: window is not defined

### ISSUE THREAD

**Issue by ritesh-bobtrade** [rcdexta/react-trello#12]
ReferenceError: window is not defined
    at Object.<anonymous> (D:\bobtrade\bobtrade-marketplace\node_modules\react-trello\dist\components\Board.js:33:61)
    at Module._compile (module.js:570:32)
    at Module._extensions..js (module.js:579:10)
    at Object.require.extensions.(anonymous function) [as .js] (D:\bobtrade\bobtrade-marketplace\node_modules\babel-register\lib\node.js:152:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (D:\bobtrade\bobtrade-marketplace\node_modules\react-trello\dist\index.js:8:14)
    at Module._compile (module.js:570:32)
    at Module._extensions..js (module.js:579:10)
    at Object.require.extensions.(anonymous function) [as .js] (D:\bobtrade\bobtrade-marketplace\node_modules\babel-register\lib\node.js:152:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (D:/bobtrade/bobtrade-marketplace/client/components/Merchant/Order/Orders.js:4:1)
    at Module._compile (module.js:570:32)
    at loader (D:\bobtrade\bobtrade-marketplace\node_modules\babel-register\lib\node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (D:\bobtrade\bobtrade-marketplace\node_modules\babel-register\lib\node.js:154:7)

**Comment by rcdexta** [comment]
Hi @ritesh-bobtrade Can you mention if you are using `react-trello` via npm or bower or trying to include the dist js file directly. The dist build is for browser only.

**Comment by ritesh-bobtrade** [comment]
hi @rcdexta i am using react-trello via npm.

**Comment by rcdexta** [comment]
The latest release of `react-trello` works with npm. Tested it since you reported this issue. Can you refer to the sample repo: https://github.com/rcdexta/react-trello-example and see if this works fine on your machine?
